export const site = {
  name: '삥이FC',
  fullName: '삥이FC(풋볼N컬처)_official',
  tagline: '축구의 역사를 놀고, 읽고, 걷는 곳',
  url: 'https://bbingefc.com',
  locale: 'ko-KR',
  author: '삥이',
  authorName: '박성호',
  email: 'sho3603@naver.com',
  naverBlog: 'https://blog.naver.com/sho3603',
  naverFashionBlog: 'https://blog.naver.com/sunghoandbbing2',
  naverEconomicsBlog: 'https://blog.naver.com/moneyomm',
  tistory: 'https://sho3603.tistory.com/',
  instagram: 'https://www.instagram.com/bbinge_26/',
  instagramOfficial: 'https://www.instagram.com/bbinge_official/',
  naverPerson: 'https://search.naver.com/search.naver?where=nexearch&query=%EC%82%A5%EC%9D%B4',
  namuwiki: 'https://namu.wiki/w/%EC%82%A5%EC%9D%B4',
  authorProfiles: [
    'https://blog.naver.com/sho3603',
    'https://blog.naver.com/sunghoandbbing2',
    'https://blog.naver.com/moneyomm',
    'https://sho3603.tistory.com/',
    'https://www.instagram.com/bbinge_26/',
    'https://www.instagram.com/bbinge_official/',
    'https://search.naver.com/search.naver?where=nexearch&query=%EC%82%A5%EC%9D%B4',
    'https://namu.wiki/w/%EC%82%A5%EC%9D%B4',
  ],
};
