export const site = {
  name: '삥이FC',
  englishName: 'BBINGE FC',
  fullName: '삥이FC(풋볼N컬처)_official',
  alternateNames: ['BBINGE FC', 'BBinge FC', '삥이FC(풋볼N컬처)_official', 'bbingefc.com'],
  tagline: '축구의 역사를 놀고, 읽고, 걷는 곳',
  homeDescription: '축구의 역사·전술·규칙·여행·유니폼을 박성호(삥이)의 관점으로 읽고 기록하는 독립 축구 문화 매거진입니다.',
  url: 'https://bbingefc.com',
  locale: 'ko-KR',
  author: '삥이',
  authorName: '박성호',
  authorAlternateNames: ['삥이', 'BBinge', 'BBingStory', 'Park Seongho', '朴誠護'],
  authorDescription: '삥이FC를 운영하며 축구의 역사·문화·산업·전술을 기록하는 기획자이자 축구사 저자입니다.',
  email: 'sho3603@naver.com',
  naverBlog: 'https://blog.naver.com/sho3603',
  naverFashionBlog: 'https://blog.naver.com/sunghoandbbing2',
  naverEconomicsBlog: 'https://blog.naver.com/moneyomm',
  tistory: 'https://sho3603.tistory.com/',
  instagram: 'https://www.instagram.com/bbinge_26/',
  instagramOfficial: 'https://www.instagram.com/bbinge_official/',
  naverPerson: 'https://search.naver.com/search.naver?where=nexearch&query=%EC%82%A5%EC%9D%B4',
  namuwiki: 'https://namu.wiki/w/%EC%82%A5%EC%9D%B4',
  naverInfluencer: 'https://in.naver.com/soccerbybbing2',
  brunch: 'https://brunch.co.kr/@c50aa0b5d6d4431',
  substack: 'https://substack.com/@bbinge',
  authorProfiles: [
    'https://blog.naver.com/sho3603',
    'https://blog.naver.com/sunghoandbbing2',
    'https://blog.naver.com/moneyomm',
    'https://sho3603.tistory.com/',
    'https://www.instagram.com/bbinge_26/',
    'https://www.instagram.com/bbinge_official/',
    'https://search.naver.com/search.naver?where=nexearch&query=%EC%82%A5%EC%9D%B4',
    'https://namu.wiki/w/%EC%82%A5%EC%9D%B4',
    'https://in.naver.com/soccerbybbing2',
    'https://brunch.co.kr/@c50aa0b5d6d4431',
    'https://substack.com/@bbinge',
  ],
};
